name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy-next:
        runs-on: ubuntu-latest
        name: Deploy Next
        steps:
            -   uses: actions/checkout@v4
            -   name: Deploy
                uses: cloudflare/wrangler-action@v3
                with:
                    apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                    command: deploy --env next
    deploy-prod:
        runs-on: ubuntu-latest
        name: Deploy Prod
        steps:
            -   uses: actions/checkout@v4
            -   name: Deploy
                uses: cloudflare/wrangler-action@v3
                with:
                    apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                    command: deploy --env prod
